version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/home/node/app
    ports:
      - '8080:8080'
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/home/node/app
    ports:
      - '3000:3000'
